### ISSUE TITLE
Refresh needed

### ISSUE THREAD

**Issue by jmailing** [integer-net/Autoshipping#22]
Hi,

At first, I would like to say thank you for this extension.
I use it with owebia shipping module. Shipping is free when >50€ and 6€ elsewhere. I am only shipping to France.
I am afraid it might be my mistake but, the plugin has a strange behavior.
If I change the quantity in the cart to switch from 50+ to 50- or vice-versa, I need to update twice the cart to have the proper shipping line to be displayed.
http://212.129.63.72/ for a demo
I have rremoved the shipping estimate block but I have tried with or without it and it does not change the problem.
What am I doing wrong ?

Best Regards,

Julien

**Comment by schmengler** [comment]
Fixed in v0.3.2
