### ISSUE TITLE
shipping method shown in the cart

### ISSUE THREAD

**Issue by Silver0023** [integer-net/Autoshipping#23]
Hi,

I downloaded and installed the extension IntegerNet_Autoshipping and it works great. but in the shopping cart the shipping method are displayed expanded. I would like only to have the text (Shipping cost). The reason is that I only have one sender but with different capabilities. All these shipping methods are equally expensive.

How can I change this.

Thanks in advance

**Comment by avstudnitz** [comment]
Sorry, the module (or Magento, as we Magento core functionality for that) doesn't support that. It always displays a specific shipping method.
