### ISSUE TITLE
Keine Lieferkosten oder 0 EUR Lieferkosten

### ISSUE THREAD

**Issue by BJockeyR** [integer-net/Autoshipping#24]
Hallo,

Nachdem ich dieses Modul installiert habe ist folgendes Problem aufgetaucht:
Ich bin als Kunde im Shop angemeldet und lege ein Produkt mit Lieferkosten in den WK.
Der Warenkorb zeigt die Lieferkosten korrekt an.
Ich melde mich ab und gleich wieder an.
Ich wechsle in den Warenkorb und es werden keine Lieferkosten angezeigt.
Ich aktualisiere den Warenkorb und die Lieferkosten sind wieder da.

Gibt es eine Möglichkeit, die Lieferkosten auch beim ersten anzeigen des Warenkorbs nach einem Login anzuzeigen?
Magento Version 1.9.0.1 (aktueller Patch Stand)
Autoshipping: 0.3.3

**Comment by avstudnitz** [comment]
Könnten Sie den "develop"-Branch des Moduls ausprobieren (https://github.com/integer-net/Autoshipping/tree/develop)?

**Comment by BJockeyR** [comment]
Hallo,
Wollte gerade schreiben dass es mit dem aktuellen develop Branch funktioniert. :)
Danke

**Comment by pipol44** [comment]
Hallo
Habe die aktuelle Version geladen. Wenn ich vom Standardland auf z..b. Deutschland klicke, erscheint bei den Lieferkosten 0.-  jedoch wenn ich den Warenkorb aktualisiere, erscheinen die korrekten Versandkosten. Gibt es eine Möglichkeit, dass der Warenkorb automatisch aktualisiert wird bei anderer Länderwahl?

Magento Version 1.9.2

**Comment by jniebergall** [comment]
Hallo Andreas, 

Kommentar von @pipol44 kann ich bestätigen. Habe das gleiche Problem in einem Projekt.



Grüße
Jonas

**Comment by jniebergall** [comment]
Hallo @avstudnitz, 

wie Du am 11.5 beschrieben hast, mit "develop" läuft es.

Danke!
Jonas
