### ISSUE TITLE
Does not recognise free shipping

### ISSUE THREAD

**Issue by anim8design** [integer-net/Autoshipping#7]
Hi, we have installed this but it does not recognise free shipping. We use flat shipping at 4.95 and then have free shipping for orders above 60.00. We only delivery to GB. It is fine with the flat rate but when we put a larger order in, it still applies the delivery charge. Can you help? Thanks.

**Comment by riker09** [comment]
What about free shipping that is calculated depending on a system configuration field value? The comments on the [Integer-Net blog post](http://www.integer-net.de/magento-versandkostenvorschau-im-warenkorb-mit-integernet_autoshipping/) from runi, Lars Bankert and Moritz all address the same issue.

**Comment by head82** [comment]
Same problem with flatrate shipping and a freeshipping basket rule. But i works fine with tablerates (+same basket rule).
